### PR TITLE
fix(dashboard): repair lecturer dashboard query, auth middleware and …

### LINKED ISSUE #40: Update lecturer dashboard to read from normalised staff and consultation tables
Parent issue: #11 Static Lecturer Dashboard

Description:
## Context
Both `staff` and `consultation` tables are normalized. The lecturer dashboard must use junction tables (`staff_courses`, `consultation_attendees`) instead of JSON parsing.

## What changes
- Replace JSON.parse on staff.courses with JOIN on `staff_courses`
- Replace JSON.parse on consultation.attendees with JOIN on `consultation_attendees`
- Update dashboard to show courses from junction table
- Display consultation attendee names via JOIN on `students`

## Acceptance Tests
- [ ] Dashboard loads with normalized schema
- [ ] Lecturer's assigned courses display correctly
- [ ] Upcoming consultations show organiser and attendee names
- [ ] Cancel button visible for consultations organised by this lecturer
- [ ] No JSON.parse calls in dashboard controller

### PR DESCRIPTION
**Pull request by ThandiAlgorithm**
## Closes #40

# Fix Lecturer Dashboard Query + Auth Protection + DoD Tests

### Lecturer Dashboard Query Fix
- Fixed lecturer dashboard always returning empty results
- Removed incorrect student-dashboard logic using `EXISTS` with `student_number`
- Replaced with correct filtering using `lecturer_id`
- Added `consultation_attendees` join to fetch attendee names properly

### Route Protection
- Added `requireAuth` middleware
- Added `requireRole('lecturer')` middleware
- Protected lecturer dashboard route so only authenticated lecturers can access it

### View Updates
- Removed past consultations section  
  (Acceptance test requires past consultations to not be shown separately)
- Added accessibility attributes to match the student dashboard standard

### File Structure Improvements
- Renamed `dashboard-controller.js` to `lecturer-dashboard-controller.js`
- Improved clarity and consistency with naming conventions

### Availability Error Handling
- Added `try/catch` to `saveAvailability()` for proper backend error handling

### Testing Improvements
- Added unit tests for lecturer dashboard stats calculation logic
- Added integration tests for:
  - dashboard access
  - role-based access control
  - correct rendering of lecturer dashboard data

## Why it was changed

This fixes issues #40 had.

### CODE REVIEW

File: src/controllers/lecturer-dashboard-controller.js [hunk 1]
```diff
@@ -0,0 +1,98 @@
+const db = require('../../database/db');
```
Comment (Aditya-Raghunandan) [inline src/controllers/lecturer-dashboard-controller.js:1]: I like the more specific name will help keep code clean

File: src/routes/dashboard-routes.js [hunk 2]
```diff
@@ -1,10 +1,11 @@
 const express = require('express');
-const { showLecturerDashboard } = require('../controllers/dashboard-controller');
+const { showLecturerDashboard } = require('../controllers/lecturer-dashboard-controller');
 const { showStudentDashboard }  = require('../controllers/student-dashboard-controller');
+const { requireAuth, requireRole } = require('../middleware/auth-middleware');
 
 const router = express.Router();
 
-router.get('/lecturer/dashboard', showLecturerDashboard);
+router.get('/lecturer/dashboard', requireAuth, requireRole('lecturer'), showLecturerDashboard);
```
Comment (Aditya-Raghunandan) [inline src/routes/dashboard-routes.js:8]: security improved

**Comment by Aditya-Raghunandan** [comment]
Good work on this — the query fix is the most important change here and it's clean. 
The controller rename makes the codebase easier to navigate going forward. 
A few inline notes below, nothing blocking.

The Coveralls failure is just a coverage drop from the new lecturer dashboard 
controller code not having full unit test coverage yet — the CI tests themselves 
pass. Fine to merge, we can bring coverage back up in a future sprint when we add 
more tests for the dashboard stats logic.

File: src/routes/dashboard-routes.js (hunk 2 above)
Comment (Aditya-Raghunandan) [reply src/routes/dashboard-routes.js:8]: Good — the route was unprotected before which was a security gap. 
Makes sense to guard it here at the router level rather than inside the controller.

File: src/controllers/availability-controller.js [hunk 3]
```diff
@@ -45,10 +45,20 @@ const saveAvailability = (req, res) => {
...
+    `).run(constId, consultation_date, consultation_time, lecturerId, Number(duration_min), Number(max_number_of_students), venue);
+  } catch (err) {
+    console.error('Save availability error:', err);
+    return res.render('availability', {
+      user: { id: lecturerId, name: req.session.userName, role: req.session.userRole },
+      availability: db.prepare('SELECT * FROM consultations WHERE lecturer_id = ?').all(lecturerId),
+      error: 'Could not save slot. Please try again.',
+      success: null
+    });
+  }
```
Comment (Aditya-Raghunandan) [inline src/controllers/availability-controller.js:61]: Correct fix. Without this, a DB error on save would crash the request with an 
unhandled exception rather than returning a user-facing error message.

File: tests/integration/studentDashboard.test.js [hunk 4]
```diff
@@ -11,8 +11,8 @@ describe('GET /student/dashboard', () => {
     expect(res.text).toContain('Past Consultations');
   });
 
-  test('shows lecturer name column header', async () => {
+  test('shows the student welcome message', async () => {
     const res = await request(app).get('/student/dashboard');
-    expect(res.text).toContain('Lecturer');
+    expect(res.text).toContain('Welcome back, Test Student');
```
Comment (Aditya-Raghunandan) [inline tests/integration/studentDashboard.test.js:16]: This test description is more accurate now — the previous assertion was testing 
the wrong thing on the student dashboard.

File: tests/unit/dashboard-controller.test.js [hunk 5]
```diff
@@ -0,0 +1,73 @@
...
+    const res = mockRes();
+    showLecturerDashboard(mockReq(), res);
+
+    expect(res.render).toHaveBeenCalledWith('lecturer-dashboard', expect.objectContaining({
+      upcomingConsultations: [],
+      stats: { daysAvailable: 0, hoursAvailable: 0, totalSlots: 0 },
+      error: 'Could not load dashboard data. Please try again.',
+    }));
+  });
+});
```
Comment (Aditya-Raghunandan) [inline tests/unit/dashboard-controller.test.js:73]: fair test coverage
